### ISSUE TITLE
Application closed unexpectly

### ISSUE THREAD

**Issue by FabianHassert** [janbeyer/FinanzApp#13]
1. Clear data and cache of the application
2. Open the app
3. Add a new profile
4. Select the profile (menu of the profile is shown)
5. Click the back button of the device

--> "FinanzApp angehalten"

**Comment by janbeyer** [comment]
Change the name and value of the GroupsActivity.PARAM_PROFILE_ID because is have to be unique.
Check if the data base is already open in getAllProfiles()

**Comment by FabianHassert** [comment]
This change can not be the solution to fix this issue.
1. You can not change the value to PARAM_GROUP_ID because it isn't the groupid!
2. You can not check if the db isopen in function getAllProfiles ... if you do this, you must do this in all functions. We must guarentee that the db isopen before we call the getAllProfiles functionality!

I have retest this usecase after revert the commit.
Maybe it is fixed while fixing issue #5 .

**Comment by janbeyer** [comment]
This is a new Problem.
In MenuActivity::onCreat() the bundle which is fetch from the intent is null after pressing the back button.
Therefore in the activateButtons() function the profileBean is also null.
Fix in Progress.

**Comment by janbeyer** [comment]
Fixed by using static fields

**Comment by FabianHassert** [comment]
I have create a class "ActivityMemory" where we can save the current profile.
We need this instance once because we need it for the transactions, too.
The error is fixed and the ProfileBean is saved in a common class.

Maybe we can change the name of the class. I have now idea how to name the class.
