### ISSUE TITLE
Analyze overview (Planning)

### ISSUE THREAD

**Issue by FabianHassert** [janbeyer/FinanzApp#16]
Create the additional analyse overview.

DISCUSS
- What fields do we need to enter
--> a start value
--> a beginn date
--> an end date
--> a button to start (after click the result is showing)
something else?

After discuss we should create new issues to implement these functions.

**Comment by janbeyer** [comment]
Planning done
Use the MpAndroid library for implementation
https://www.studytutorial.in/android-pie-chart-using-mpandroid-library-tutorial
