### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by FabianHassert** [janbeyer/FinanzApp#17]
DISCUSS
We should discuss how to make the application more beautiful!
Currently we use the standard formats and just define some colours.
-> Menues
-> Fonts
-> Icons
-> Colours
-> Buttons
-> Backgrounds
-> Input fields
-> Validation
........

After discuss this we should close the planning issue and create new issues for the functions to implement.

**Comment by ElBuderino** [comment]
Basic application design was implemented.
