### ISSUE TITLE
Add the following abstract classes

### ISSUE THREAD

**Issue by FabianHassert** [janbeyer/FinanzApp#18]
Java:
- AbstractDataSource
- AbstractDBHelper
- AbstractBaseActivity
- BasicContextualActionBar
- BasicMainMenu

Xml:
- ContextualActionBar (Menu)
- MainMenu

**Comment by FabianHassert** [comment]
Currently there exist a lot of abstract classes.
Which abstract classes are open to implement?

**Comment by janbeyer** [comment]
Fixed
