### ISSUE TITLE
Profile name not set in Title

### ISSUE THREAD

**Issue by FabianHassert** [janbeyer/FinanzApp#22]
1. Select a profile -> Profile name is set in the title of the menu activity
2. Click the button "Groups"
3. Click the back button -> Profile name is not set in the title of the menu activity

**Comment by FabianHassert** [comment]
To fix this bug issue #13 must be fixed.
To fix this bug issue #18 must be fixed.

**Comment by janbeyer** [comment]
Fixed using statics
