### ISSUE TITLE
Define texts for the help views

### ISSUE THREAD

**Issue by FabianHassert** [janbeyer/FinanzApp#26]
We must define the text for the help views
- Profile
- Menu
- Groups
- Transactions
- Analyse
We must define the texts for the language [de] and [en].
Please use the properties (in string.xml):

    <string name="help_profile_text">TODO: Help profile text</string>
    <string name="help_menu_text">TODO: Help menu text</string>
    <string name="help_group_text">TODO: Help group text</string>

**Comment by swenkrause** [comment]
First step is done, the help-texts for 

Profile, Menu, Transactions are imlementet in both languages, english and german.

Groups has to be extended.

Analyse will be implementet, when the feature is ready to use.

**Comment by swenkrause** [comment]
There is a scrollbar needed in the popup, to watch the full text, when it is longer than the display or if the display is turned.

**Comment by FabianHassert** [comment]
TODO
- Implement Scrollbar in Help Popup Dialog
- Texts for Analyse Activity (if implemented)

**Comment by FabianHassert** [comment]
I have implement and commit a scrollbar in the help popup dialog.

**Comment by swenkrause** [comment]
review the help-texts and adapt the changes made, for example:
transaction income or expenditure is defined by positiv or negative value and no longer by choosing an option in the dialogue as described in the help-text.

**Comment by FabianHassert** [comment]
Swen Krause told me to close this issue.
