### ISSUE TITLE
B: Add/Edit Transaction - State

### ISSUE THREAD

**Issue by FabianHassert** [janbeyer/FinanzApp#33]
B0:
Radio buttons one below the other.
The needed fields for the radio buttons besides.
###########
B1:
1 = Unique
--> DatePicker
--> Date must be a valid date if this radio button is selected
###########
B2:
2 = Daily
###########
B3:
3 = Weekly
--> Dropdownbox (Monday ... Sunday)
--> Default is Monday
###########
B4:
4 = Monthly
--> Dropdownbox (1 ... 31)
--> Default is 1
###########
B5:
5 = Yearly
--> Dropdownbox (1 ... 12)
--> Default is 1
--> Dropdownbox (1 ... 31)
--> Default is 1
--> Optional: Valid date i.e. 31.02 is not possible

**Comment by FabianHassert** [comment]
B1: After click the radio button for a "unique" transaction, an date picker opens --> That works.
a) If I select a date, this date isn't shown in the dialog.
b) It is possible to select the radio button and click the button cancel. If the user clicks the button cancel we should set a default value (see c)).
c) Currently the default 2000:01:01 is set. In my opinion it is the best to select the current date for the default value.
d) We should use a valid date format. E.g. in english "2018-11-25" and in german "25.11.2018".

**Comment by janbeyer** [comment]
Implement B3, B4 and B5
Validation is still open

**Comment by FabianHassert** [comment]
Review of this Feature:

1. Uniquely
a. This should be the first radio button.
b. After select a value it is not possible to see which value is selected. We should show this e.g. in a textfield.
c. By save a unique transaction we save more information than we need. DayOfWeek is 1 ; monthlyDay is 1 ; yearlyMonth is 1 ; yearlyDay is 1 --> We shouldn't need this values and should write null into the db.
d. By edit this transaction the radio button has not the value unique. The radio button has the value daily and this is not correct.

2. Daily
a. Same like 1c)
b. Same like 1d)

3. Weekly
a. Why is there an additional popup to select the dates in a dropdownbox? We should not need this popup. We should show the dropdownbox right next to the radio button.
b. Select a value like "Wednesday" and close the popup. If I would like to change the value I aspect, that the selected value is preselected. This is not the case. Instead of this, Monday is selected.
c. After select a value it is not possible to see which value is selected. We should show this e.g. in a textfield.
d. The saved DayOFWeek is not like the Calendar.DAY_OF_WEEK (see Api)
e. Same like 1c)
f. Same like 1d)

4. Monthly
a. Same like 3a)
b. Same like 3b) for the days
c. Same like 3c)
d. Same like 1c)
e. Samle like 1d)
f. The monthly day is not saved into the db.
g. UI: The dropdown where to select the days is not really nice ... we should design this in a better way

5. Yearly
a. Same like 3a)
b. Same like 3b) for the month and days
c. Same like 3c)
d. Same like 1c)
e. Same like 1d)
f. There is no description which dropdownbox is the month and which is the day
g. There is a missing event handler which refresh the date-dropdown after select the month. E.g. for the Februar it should not be possible to select the day 29, 30 and 31.
h. The yearly month and day is not saved into the db.
i. Same like 4g)

Common
a. If we further use these popup-dialogs (I have no arguments why (except the unique date)) we should not use the button "Cancel" because the user would like to "Confirm" his selected choice. If I am the user and I would click on the button "Cancel" I have the feeling to cancel my inputs.

We should implement this asap.

**Comment by FabianHassert** [comment]
Close this issue.
We should add short issues with a specific advice.
