### ISSUE TITLE
Analysis: Logical Part

### ISSUE THREAD

**Issue by FabianHassert** [janbeyer/FinanzApp#36]
- Startvalue
- VonDatum
- BisDatum
- Startbutton
--> after click calculate the analysis bean object

Anzahl Einnahmen / Summe Einnahmen / Mittelwert / Median
Anzahl Ausgaben / Summe Ausgaben / Mittelwert / Median
Summe Anzahl / Summe = Verlust / Erspartes / Mittelwert / Median

**Comment by FabianHassert** [comment]
The logical part is implemented and tested.
Currently missing is the frontend to enter the startDate and endDate.

**Comment by swenkrause** [comment]
the programming of these tests is done.
