### ISSUE TITLE
GUI: Colour

### ISSUE THREAD

**Issue by FabianHassert** [janbeyer/FinanzApp#41]
Currently we use the color red in our application. 
In my opinion the color red is the colour of something which is not correct like a failure (or in our cases a validation error or the outgoing amounts in the diagram).

a) We should use other colours
b) We should use weaker colours
--> currently we can select elements of the listview. This selected items should be in weaker colour because it is difficult to read the text
c) We should use a range of colours like different types of a colour (e.g. use http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF)

**Comment by janbeyer** [comment]
New color shema suggestion

**Comment by janbeyer** [comment]
Layout approved
