### ISSUE TITLE
Back button in group activity doesn't work

### ISSUE THREAD

**Issue by FabianHassert** [janbeyer/FinanzApp#5]
Open the group overview ... click the back button in the upper left corner ... doesn't work.
Open the group overview ... click the back button of the smartphone ... works.

I don't know why it doesn't work, because I set the parent activities in the manifest.xml.
It is the same procedure like in the menu activity. Therfore it works to click the back button and the profile activity resumes.

**Comment by janbeyer** [comment]
Fixed by deleting the functions  onCreateOptionsMenu() and onOptionsItemSelected() which overwrite the functions from the base class.
